#查询时是否只使用自己绑定的CK
onlySelfCk: false

# 米游社国际服代理
proxy:
  host: 
  port: 

# components中的额外功能
plugins: []

#使用wkhtmltoimage渲染图片
wkhtmltoimage: false

#使用wkhtmltoimage渲染图片的端口(填写端口时资源使用http路径、重启后生效)
wkhtmltoimagePort:  false

#渲染精度(0-100)
quality: 100